# Generated by Django 3.1.1 on 2022-01-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_ID', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
