# Generated by Django 3.1.1 on 2022-01-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_registeruser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='email_ID',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='password',
        ),
    ]
