# Generated by Django 3.1.1 on 2022-01-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220102_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='profile_pic_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
